# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'insulin_calculator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for insulin_calculator
  # pod 'SVProgressHUD'

  target 'insulin_calculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'insulin_calculatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
